apiVersion: platform.homelab.io/v1alpha1
kind: App
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: sample-service
  namespace: sample-application-staging
spec:
  crossplane:
    compositionRef:
      name: app-kubernetes
  parameters:
    config:
      LOG_LEVEL: info
    environment: staging
    exposure:
      host: sample-service.example.com
      type: none
    healthCheck:
      liveness: /healthz
      readiness: /readyz
    image: ghcr.io/mohamediag/sample-service:f9cc30c
    metrics:
      enabled: true
      path: /metrics
    name: sample-service
    owner: team-platform
    port: 8080
    replicas: 1
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
    secrets:
    - DUMMY_SECRET

