# ==============================================================================
# ansible-inventory.tf — Generate Ansible inventory from Terraform state
# ==============================================================================
# After `terraform apply`, this generates ansible/inventory/hosts.yml
# which Ansible uses to know which hosts to manage and how to reach them.
#
# All VMs are accessed via SSH ProxyJump through the Hetzner host.
# Groups created:
#   - hetzner_host   — the bare-metal Hetzner server (direct SSH as root)
#   - control_plane  — Kubernetes control plane nodes
#   - workers        — Kubernetes worker nodes
#   - k8s_nodes      — all VM nodes (control_plane + workers combined)
# ==============================================================================

locals {
  # Separate VMs by role for inventory grouping
  control_planes = {
    for name, def in var.vm_definitions : name => def if def.role == "control_plane"
  }
  workers = {
    for name, def in var.vm_definitions : name => def if def.role == "worker"
  }

  # Absolute path to the VM SSH private key (generated by ssh-keys.tf)
  # abspath() ensures this works regardless of which directory terraform is run from
  vm_key_path = abspath("${path.root}/files/vm_key")

  # ProxyJump args used for all VM connections (SSH through Hetzner host to VMs)
  proxy_jump_args = "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyJump=root@${var.hetzner_host_ip} -i ${local.vm_key_path}"
}

resource "local_file" "ansible_inventory" {
  filename = abspath("${path.root}/../ansible/inventory/hosts.yml")

  content = yamlencode({
    all = {
      children = {

        # ── Hetzner bare-metal host ───────────────────────────────────────────
        # Direct SSH connection as root — no ProxyJump needed
        hetzner_host = {
          hosts = {
            hetzner = {
              ansible_host                 = var.hetzner_host_ip
              ansible_user                 = "root"
              ansible_ssh_private_key_file = var.ssh_key_path
              ansible_ssh_common_args      = "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
            }
          }
        }

        # ── Kubernetes control plane nodes ────────────────────────────────────
        control_plane = {
          hosts = {
            for name, def in local.control_planes : name => {
              ansible_host                 = def.ip
              ansible_user                 = "kubeadmin"
              ansible_ssh_private_key_file = local.vm_key_path
              ansible_ssh_common_args      = local.proxy_jump_args
            }
          }
        }

        # ── Kubernetes worker nodes ───────────────────────────────────────────
        workers = {
          hosts = {
            for name, def in local.workers : name => {
              ansible_host                 = def.ip
              ansible_user                 = "kubeadmin"
              ansible_ssh_private_key_file = local.vm_key_path
              ansible_ssh_common_args      = local.proxy_jump_args
            }
          }
        }

        # ── All K8s VMs (used by common/containerd/kubeadm playbooks) ─────────
        k8s_nodes = {
          children = {
            control_plane = {}
            workers       = {}
          }
        }
      }
    }
  })

  # Ensure the inventory directory exists
  depends_on = [
    module.vms,
  ]
}
