apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    app.platform.homelab.io/application: sample-application
    app.platform.homelab.io/environment: prod
    app.platform.homelab.io/team: team-platform
  name: sample-application-prod

