apiVersion: platform.homelab.io/v1alpha1
kind: App
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: sample-service
  namespace: sample-application-prod
spec:
  crossplane:
    compositionRef:
      name: app-kubernetes
  parameters:
    config:
      LOG_LEVEL: info
    environment: prod
    exposure:
      host: sample-service.example.com
      type: none
    healthCheck:
      liveness: /healthz
      readiness: /readyz
    image: ghcr.io/mohamediag/sample-service:5423e64
    metrics:
      enabled: true
      path: /metrics
    name: sample-service
    owner: team-platform
    port: 8080
    replicas: 2
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    secrets:
    - DUMMY_SECRET

