apiVersion: platform.homelab.io/v1alpha1
kind: App
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: sample-service
  namespace: sample-application-dev
spec:
  crossplane:
    compositionRef:
      name: app-kubernetes
  parameters:
    config:
      LOG_LEVEL: debug
    environment: dev
    exposure:
      host: sample-service.example.com
      type: none
    healthCheck:
      liveness: /healthz
      readiness: /readyz
    image: ghcr.io/mohamediag/sample-service:e42bf0d
    metrics:
      enabled: true
      path: /metrics
    name: sample-service
    owner: team-platform
    port: 8080
    replicas: 1
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 25m
        memory: 32Mi
    secrets:
    - DUMMY_SECRET

