apiVersion: v1
kind: Namespace
metadata:
  name: team-platform-sample-application-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    app.platform.homelab.io/team: team-platform
    app.platform.homelab.io/application: sample-application
    app.platform.homelab.io/environment: dev
